let songsObject = [
    {
        id: 1,
        name: 'Blinding Lights',
        artist: 'The Weeknd',
        artist_cover_src: '/images/weeknd.jpg',
        track_src: '/tracks/1.mp3',
        artist_cover: 'empty',
        song_cover: 'empty',
        duration: 'empty',
    },

    {
        id: 2,
        name: 'Closer',
        track_src: '/tracks/2.mp3',
        artist: 'The Chainsmokers',
        artist_cover_src: '/images/chainsmokers.jpg',
        artist_cover: 'empty',
        song_cover: 'empty',
        duration: 'empty',
    },
    {
        id: 3,
        name: 'Girls Like You',
        artist: 'Maroon 5',
        artist_cover_src: '/images/maroon_5.jpeg',
        track_src: '/tracks/3.mp3',
        artist_cover: 'empty',
        song_cover: 'empty',
        duration: 'empty',
    },
    {
        id: 4,
        name: 'As It Was',
        artist: 'Harry Styles',
        track_src: '/tracks/4.mp3',
        artist_cover_src: '/images/harry_styles.jpg',
        artist_cover: 'empty',
        song_cover: 'empty',
        duration: 'empty',
    },
    {
        id: 5,
        name: 'Sugar',
        artist: 'Maroon 5',
        artist_cover_src: '/images/maroon_5.jpeg',
        track_src: '/tracks/9.mp3',
        artist_cover: 'empty',
        song_cover: 'empty',
        duration: 'empty',
    },
    {
        id: 6,
        name: 'One Kiss',
        artist: 'Calvin Harris',
        track_src: '/tracks/5.mp3',
        artist_cover_src: '/images/calvin_harris.jpg',
        artist_cover: 'empty',
        song_cover: 'empty',
        duration: 'empty',
    },
    {
        id: 7,
        name: 'Summer',
        artist: 'Calvin Harris',
        track_src: '/tracks/7.mp3',
        artist_cover_src: '/images/calvin_harris.jpg',
        artist_cover: 'empty',
        song_cover: 'empty',
        duration: 'empty',
    },
    {
        id: 8,
        name: 'Starboy',
        artist: 'The Weeknd',
        artist_cover_src: '/images/weeknd.jpg',
        track_src: '/tracks/6.mp3',
        artist_cover: 'empty',
        song_cover: 'empty',
        duration: 'empty',
    },
    {
        id: 9,
        name: 'Golden',
        artist: 'Harry Styles',
        track_src: '/tracks/8.mp3',
        artist_cover_src: '/images/harry_styles.jpg',
        artist_cover: 'empty',
        song_cover: 'empty',
        duration: 'empty',
    },

]

export default songsObject